### PR TITLE
Added Charge customer at for Posting Bills

### PR DESCRIPTION
**Pull request by w3developments**
Extended PostBill method to accept Charge Customer At parameter and included additional property in BillResponse  class to match response from GoCardless

### CODE REVIEW

**Comment by timrogers** [comment]
@w3developments Thanks for taking the time to add this functionality to the library - have you been able to get it working okay in your testing?

@banderous Can you run specs and get this released please?

**Comment by w3developments** [comment]
@timrogers I ran a couple of sandbox tests, one with a null and one with a date and both appeared to function correctly. Another option would be to overload the PostBill method so one has a parameter for charge customer at and one doesn't. Not sure if this would be a safer proposal for backwards compatibility or not.

The one with a date sent an email saying a payment had been scheduled for xxxx. The one without just said a payment had been charged.

Obviously if you wanted to not include name & description, but include a date you could just pass PostBill(billRequest,authorizationId,null,null,DateTime).

I did have a think afterwards about globalization and cultures, but I think the format method I used should allow for this, as it explicitly defines the date format. Might be something to just check.

Sorry, I think I may have rolled them into my company name and toggle commit without realising. I'm not a github expert so I added the code to my own fork, without starting a new one.

**Comment by timrogers** [comment]
@w3developments All looks broadly good to me, but I'm by no means a .NET
expert. @banderous will be able to have a look and get this released
hopefully.

## 

_Tim Rogers_
Account Manager
GoCardless.com https://gocardless.com

020 3397 7527

**Comment by DanielPLyons** [comment]
@banderous Quick reminder, can you take a look at this.

**Comment by jacobpgn** [comment]
Hey @banderous - another customer request for this

**Pull request merged**
