### PR TITLE
Added ability to cancel bills via API

### PR DESCRIPTION
**Pull request by kitgocardless**

### CODE REVIEW

**Comment by kitgocardless** [comment]
@greysteil now that Alex is gone, who would be the best person to review changes to the .NET library?

@jacobpgn FYI

**Comment by greysteil** [comment]
Possibly @hirokitakeuchi

**Comment by hirokitakeuchi** [comment]
Hhhhhmmm.. I have never actually used the .net library, and my understanding of the code is shaky at best (I received tutoring from the venerable Hugh Smith). 

I can have a stab at running the specs, but other than that I have as good an idea as anyone whether this is good code!

**Comment by hirokitakeuchi** [comment]
Ok - can't even seem to run the specs for this! @hmarr any ideas on getting these reviewed?

**Comment by jacobpgn** [comment]
💔

**Pull request closed without merging**
